name: 🤖 Auto label
on: pull_request_review

jobs:
  label-when-approved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.9.2
      - uses: taiga-family/ci/actions/label-when-approved@1.9.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
