name: ⚙️ Lint
on:
  pull_request:
  push:
    branches: [main]

jobs:
  typecheck:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/setup-node@1.9.2
      - run: npm run typecheck

  cspell:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/setup-node@1.9.2
      - run: npm run cspell -- --no-progress

  prettier:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.9.2

      - uses: actions/checkout@v3.5.3
        if: env.SUPPORT_AUTO_PUSH == 'true'
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

      - uses: taiga-family/ci/actions/setup-node@1.9.2

      - run: npm run prettier ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --write' || '-- --check' }}

      - name: Apply changes after linting
        if: env.SUPPORT_AUTO_PUSH == 'true'
        uses: taiga-family/ci/actions/auto-push@1.9.2

  stylelint:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.9.2

      - uses: actions/checkout@v3.5.3
        if: env.SUPPORT_AUTO_PUSH == 'true'
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

      - uses: taiga-family/ci/actions/setup-node@1.9.2
      - run: npm run stylelint ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --fix' || '' }}

      - name: Apply changes after linting
        if: env.SUPPORT_AUTO_PUSH == 'true'
        uses: taiga-family/ci/actions/auto-push@1.9.2

  eslint:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: taiga-family/ci/actions/variables@1.9.2

      - uses: actions/checkout@v3.5.3
        if: env.SUPPORT_AUTO_PUSH == 'true'
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.TAIGA_FAMILY_BOT_PAT }}

      - uses: taiga-family/ci/actions/setup-node@1.9.2
      - run: npm run lint ${{ env.SUPPORT_AUTO_PUSH == 'true' && '-- --fix' || '' }}

      - name: Apply changes after linting
        if: env.SUPPORT_AUTO_PUSH == 'true'
        uses: taiga-family/ci/actions/auto-push@1.9.2

concurrency:
  group: lint-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
